### github-action-variable-03.yml

name: Test Github Action Variable 03
run-name: Github Actions Var, secret
on: 
  workflow_dispatch

jobs:
  check-vars-context:
    runs-on: ubuntu:latest
    steps:
      - name: "Hello, Var_Test"
        run: echo "Hello, ${{ vars.VAR_TEST }}"
  check-secrets-context:
    runs-on: ubuntu:latest
    steps:
      - name: "Hello, secrets_Test"
        run: echo "Hello, ${{ secrets.SECRET_TEST }}"
        
