### github-action-checkout-01.yml

name: Test Github Action Checkout 01
run-name: Github Actions Checkout
on: 
  workflow_dispatch
    

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Print ls
        run: ls -al
        
      - name: Github Actions Checkout
        uses: actions/checkout@v4
        with:
          path: checkout-dir

      - name: Github Actions Checkout(otehrs repository)
        uses: actions/checkout@v4
        with:
          repository: actions/checkout
          path: otehr-repo

      - run: ls -al
