### github-action-variable-04.yml

name: Test Github Action Variable 04
run-name: Github Actions inputs, outputs, needs 
on: 
  workflow_dispatch:
    inputs:
      name:
        description: '이름-영소문자'
        required: true
        default: 'input'

jobs:
  input-data:
    runs-on: ubuntu-latest
    outputs:
      upper_name: ${{ steps.uppercase.outputs.result }}
    steps:
      - name: Print input data
        id: uppercase
        run: echo "result=$(echo '${{ github.event.inputs.name }}' | tr 'a-z' 'A-Z')" >> $GITHUB_OUTPUT
  
  output_data:
    runs-on: ubuntu-latest
    steps:
      - name: Print output data
        run: echo "Hello, ${{ needs.input-data.outputs.upper_name }}"
