### github-action-checkout-01.yml

name: Test Github Action Checkout 01
run-name: Github Actions Checkout
on: 
  push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Print ls
        run: ls -al
        
      - name: Github Actions Checkout
        uses: actions/checkout@v4
        with:
          path: checkout-dir
      - run: ls -al
